# http://travis-ci.org/#!/Stub-O-Matic/stubo-app
language: python
python:
    - 2.7

cache: pip
  
install:
    - travis_retry python setup.py install
    - travis_retry pip install coveralls

services:
  - redis-server
  - mongodb

# command to run tests
script: 
  - export STUBO_CONFIG_FILE_PATH=./dev.ini
  - nosetests --with-coverage --cover-package=stubo
  
after_success:
    coveralls  
