# http://travis-ci.org/#!/Stub-O-Matic/stubo-app
language: python
python:
    - 2.7
  
install:
    - python setup.py install

services:
  - redis-server
  - mongodb

# command to run tests
script: 
  - export STUBO_CONFIG_FILE_PATH=.
  - nosetests stubo
